version: '3.9'
services:
  mongodb:
    container_name: db_container
    image: mongo
    restart: always
    ports:
      - 8081:8081
    volumes:
      - ~/apps/mongo:/data/db
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: sonne123#
      MONGO_DB: nest
    networks:
      - beinsascores
networks:
  beinsascores:
